<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <EnForceExtendedAnalyzerRules>true</EnForceExtendedAnalyzerRules>
        <SatelliteResourceLanguages>xx</SatelliteResourceLanguages>
    </PropertyGroup>

	<PropertyGroup>
		<AssemblyVersion>10.0.0.0</AssemblyVersion>
		<Version>10.26.410.2</Version>
		<FileVersion>10.26.410.2</FileVersion>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Authors>Fish Li</Authors>
		<PackageId>ClownFish.EntityProxyGen</PackageId>
		<Description>ClownFish.net配套的数据实体代理类型源码生成器</Description>
		<PackageProjectUrl>https://github.com/fish-li/ClownFish.net</PackageProjectUrl>
	</PropertyGroup>

	<ItemGroup>
		<!-- Package the generator in the analyzer directory of the nuget package -->
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

    <ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces"
                          Version="4.5.0"
                          PrivateAssets="all" />
    </ItemGroup>

</Project>
