<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
        <RootNamespace>ClownFish.Web.UnitTest</RootNamespace>
        <AssemblyName>ClownFish.Web.UnitTest</AssemblyName>
        <SatelliteResourceLanguages>xx</SatelliteResourceLanguages>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningsAsErrors />
        <OutputPath>bin</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <OutputPath>bin</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\..\src\ClownFish.net\GlobalUsing.cs" Link="GlobalUsing.cs" />
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
        <PackageReference Include="MSTest.TestAdapter" Version="3.6.3" />
        <PackageReference Include="MSTest.TestFramework" Version="3.6.3" />
        <PackageReference Include="coverlet.collector" Version="1.0.1" />
        <PackageReference Include="JWT" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ClownFish.net\ClownFish.net.csproj" />
        <ProjectReference Include="..\..\src\ClownFish.Web\ClownFish.Web.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="ClownFish.Appconfig.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="ClownFish.Web.UnitTest.config.ini">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Test_ProxyMapRule.xml">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Test_ProxyMapRule2.xml">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
