<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net45;net462;net48;net8.0;net9.0;net10.0</TargetFrameworks>
        <RootNamespace>ClownFish</RootNamespace>
        <AssemblyVersion>10.0.0.0</AssemblyVersion>
        <Version>10.25.1222.1</Version>
        <FileVersion>10.25.1222.1</FileVersion>
        <SatelliteResourceLanguages>xx</SatelliteResourceLanguages>
        <OutputPath>bin</OutputPath>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <DocumentationFile>bin\ClownFish.netfx.xml</DocumentationFile>
        <!--<LangVersion>13.0</LangVersion>-->
        <LangVersion>latest</LangVersion>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageId>ClownFish.netfx</PackageId>
        <Authors>Fish Li</Authors>
        <PackageProjectUrl>https://github.com/fish-li/ClownFish.net</PackageProjectUrl>
        <Description>一个“小而美”的.NET工具类库</Description>
    </PropertyGroup>


    <ItemGroup>
        <None Remove="WebApi\Controllers\FileListTemplate.html" />
        <EmbeddedResource Include="WebApi\Controllers\FileListTemplate.html" />
    </ItemGroup>

    <ItemGroup Condition=" '$(TargetFramework)' == 'net45' or '$(TargetFramework)' == 'net462' or '$(TargetFramework)' == 'net48' ">
        <Reference Include="System.IO.Compression" />
        <Reference Include="System.Web" />
        <Reference Include="System.Configuration" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ClownFish.net\ClownFish.net.csproj" />
    </ItemGroup>


</Project>
