<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net8.0;net462</TargetFrameworks>
        <RootNamespace>ClownFish.Email</RootNamespace>
        <AssemblyVersion>10.0.0.0</AssemblyVersion>
        <Version>10.26.305.1</Version>
        <FileVersion>10.26.305.1</FileVersion>
        <SatelliteResourceLanguages>xx</SatelliteResourceLanguages>
        <OutputPath>bin</OutputPath>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <DocumentationFile>bin\ClownFish.Email.xml</DocumentationFile>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageId>ClownFish.Email</PackageId>
        <Authors>Fish Li</Authors>
        <PackageProjectUrl>https://github.com/fish-li/ClownFish.net</PackageProjectUrl>
        <Description>基于ClownFish.net的Email简单封装工具类库</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.6.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ClownFish.net\ClownFish.net.csproj" />
    </ItemGroup>

</Project>
