using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using ClownFish.Base.Reflection;
using ClownFish.Data.CodeDom;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ClownFish.EntityProxyGen.Tests;

[TestClass]
public class GenerateExpectedFilesByCodeDom
{
    internal static readonly string ModelsDir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "../../../Models");
    internal static readonly string GeneratedDir = Path.Combine(ModelsDir, "_CodeDomGen");

    private static readonly string s_codeHeader = @"// <auto-generated />
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using ClownFish.Data;
using ClownFish.Data.Internals;

";

    [TestMethod]
    public void CreateAllProxyLoaderFiles()
    {
        Directory.CreateDirectory(GeneratedDir);
        Directory.GetFiles(GeneratedDir, "*", SearchOption.TopDirectoryOnly)
                .ToList()
                .ForEach(f => File.Delete(f));

        MethodInfo method = typeof(GenerateExpectedFilesByCodeDom).GetMethod(nameof(GenEntityProxyLoaderCode), BindingFlags.NonPublic | BindingFlags.Static);

        Type[] allTypes = GetAllEntityTypes();
        foreach( Type type in allTypes ) {
            
            MethodInfo method2 = method.MakeGenericMethod(type);
            string code = (string)method2.Invoke(null, null);

            string filename = $"{type.Name}.proxy.expected.cs";
            string filepath = Path.Combine(GeneratedDir, filename);
            File.WriteAllText(filepath, s_codeHeader + code, Encoding.UTF8);
        }
    }

    private static Type[] GetAllEntityTypes()
    {
        Assembly asm = typeof(GenerateExpectedFilesByCodeDom).Assembly;
        return (from t in asm.GetPublicTypes()
                let a = t.GetCustomAttribute< DbEntityAttribute>()
                where t.IsClass && a != null
                select t).ToArray();
    }

    private static string GenEntityProxyLoaderCode<T>() where T : Entity, new()
    {
        EntityGenerator g = new EntityGenerator();
        return g.GetCode<T>();
    }
}
