<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <ServerGarbageCollection>false</ServerGarbageCollection>
        <!--<PublishAot>true</PublishAot>-->
        <!--<InvariantGlobalization>true</InvariantGlobalization>-->
        <SatelliteResourceLanguages>xx</SatelliteResourceLanguages>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\..\src\ClownFish.net\GlobalUsing.cs" Link="GlobalUsing.cs" />
    </ItemGroup>

    <ItemGroup>
        <!--<ProjectReference Include="..\..\src\ClownFish.net\ClownFish.net.csproj" />-->
        <PackageReference Include="ClownFish.net" Version="9.25.1020.3" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql" Version="7.0.6" />
        <PackageReference Include="MySqlConnector" Version="2.2.7" />
        <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
        <!--<PackageReference Include="System.Data.SQLite.Core" Version="1.0.114.3" />-->
    </ItemGroup>

    <ItemGroup>
        <None Update="App_Data\XmlCommand\Test1.config">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="ClownFish.App.config">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="ClownFish.Log.config">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="_local.env">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
