##### ClownFish.LogConfig #####
[Logging]

; 是否启用日志写入功能，总开关
Enable=true

;异步写入的间隔时间，单位：毫秒
TimerPeriod=500

;性能日志的阀值参数，超过这个阀值将会记录到性能日志中，单位：毫秒
Performance_HttpExecute=100
Performance_HandleMessage=200

; 日志文件相关配置
File_RootPath=Logs
File_MaxLength=500M
File_MaxCount=100

[Logging.Writers]
; 定义一些默认的写入器，格式： name = type-fullname
txt     =ClownFish.Log.Writers.TxtWriter, ClownFish.net
Xml     =ClownFish.Log.Writers.XmlWriter, ClownFish.net
Json    =ClownFish.Log.Writers.JsonWriter, ClownFish.net
Json2   =ClownFish.Log.Writers.Json2Writer, ClownFish.net

http    =ClownFish.Log.Writers.HttpJsonWriter, ClownFish.net
ES      =ClownFish.Log.Writers.ElasticsearchWriter, ClownFish.net
OpEs    =ClownFish.Log.Writers.OprlogEsWriter, ClownFish.net
Rabbit2 =ClownFish.Log.Writers.RabbitHttpWriter, ClownFish.net

[Logging.DataTypes]
;定义支持的数据类型，并为每种数据类型配置使用哪种写入器，
;如果某个数据类型同时指定了多个写入器，将会以不同的持久化方式同时记录多次
ClownFish.Log.Logging.OprLog, ClownFish.net      =NULL
ClownFish.Log.Logging.InvokeLog, ClownFish.net   =NULL




